version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    user: "${UID}:${GID}"
    ports:
      - 5400:8080
    volumes:
      - ./config:/config
      - /home/unsteelix:/data/Flash
      - /mnt/SSD:/data/SSD
    environment:
      - FB_BASEURL=/filebrowser
    restart: unless-stopped
