version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
#      - "67:67/udp"  # Required only for using Pi-hole as a DHCP server
      - "8000:80/tcp"
    environment:
      TZ: 'Asia/Tokyo'
      WEBPASSWORD: ${PASSWORD}
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'    
    cap_add:
      - NET_ADMIN
    restart:
      unless-stopped
